#ifndef MCAL_SPI_SPI_CFG_H_
#define MCAL_SPI_SPI_CFG_H_

//for N5110 must be master, with clock less than 4M and 8bit data
/*
	SSI_MODE_MASTER
	SSI_MODE_SLAVE_OUTPUT_ENABLED
	SSI_MODE_MASTER_OUTPUT_DISABLED
*/

#define SSI_MS_MODE 		SSI_MODE_MASTER

/*
	SSI_SYS_CLK
	SSI_PIOSC
*/
#define SSI_CLK_SOURCE 		SSI_SYS_CLK

/*
	SSI_PRESCALLER_DIV(2)
	SSI_PRESCALLER_DIV(4)
	SSI_PRESCALLER_DIV(6)
	SSI_PRESCALLER_DIV(8)
	.
	.
	.
	SSI_PRESCALLER_DIV(254)
*/

#define SSI_PRESCALLER_DIVISOR 		SSI_PRESCALLER_DIV(5)

/*
	SSI_SERIAL_CLOCK(0)
	SSI_SERIAL_CLOCK(1)
	SSI_SERIAL_CLOCK(2)
	SSI_SERIAL_CLOCK(3)
	.
	.
	.
	SSI_SERIAL_CLOCK(255)
*/

#define SSI_SERIAL_CLOCK_RATE 		SSI_SERIAL_CLOCK(0)

/*
	SSI_FRAME_FORMAT_FREESCALE
	SSI_FRAME_FORMAT_TEXAS_INSTRUMENTS
	SSI_FRAME_FORMAT_MICROWIRE
*/

#define SSI_FRAME_FORMAT 		SSI_FRAME_FORMAT_FREESCALE

/*
	SSI_POLARITY_SELECT_LOW
	SSI_POLARITY_SELECT_HIGH
*/

#define SSI_POLARITY_SELECT 		SSI_POLARITY_SELECT_LOW

/*
	SSI_PHASE_SELECT_LOW
	SSI_PHASE_SELECT_HIGH
*/

#define SSI_PHASE_SELECT 		SSI_PHASE_SELECT_LOW

/*
	SSI_DATA_BIT_SIZE(4)
	SSI_DATA_BIT_SIZE(5)
	SSI_DATA_BIT_SIZE(6)
	SSI_DATA_BIT_SIZE(7)
	.
	.
	.
	SSI_DATA_BIT_SIZE(16)
*/

#define SSI_DATA_SIZE 		SSI_DATA_BIT_SIZE(8)


#endif /* MCAL_SPI_SPI_CFG_H_ */
